export const todoConstants = {
  MARK_ALL_TODO_AS: 'MARK_ALL_TODO_AS',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  SET_EDITING_TODO: 'SET_EDITING_TODO',
  CHANGE_FILTER: 'CHANGE_FILTER',
  REMOVE_COMPLETED_TODOS: 'REMOVE_COMPLETED_TODOS',
};